backend:
  name: github
  repo: mocmienzh/mocmien

media_folder: "/public/images"
public_folder: "/images"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Các bài viết" # Used in the UI
    folder: "/src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ảnh đầu trang", name: "mainImg", widget: "image" }
      - { label: "Ngày đăng", name: "pubDate", widget: "datetime" }
      - { label: "Nội dung", name: "body", widget: "markdown" }